# -*- coding: utf-8 -*-
"""P1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lHEQ1pdCVVoXOQA7yy076NLEw8fe9i-e
"""

'''
# Define the chessboard
checkerboard = [
    [1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
]
'''

x1, y1 = map(int, input().split())
x2, y2 = map(int, input().split())

def valid_move(x1, y1, x2, y2) :
    if abs(x1 - x2) <= 1 and abs(y1 - y2) <= 1 and (x1, y1) != (x2, y2):
        if checkerboard[x2][y2] == 0:
            return True
    return False

if valid_move(x1, y1, x2, y2) == True :
    print("Yes")
else:
    print("No")